export {
  configRoot,
  defaultAntigravity2ConfigPath,
  defaultAntigravityCliConfigPath,
  defaultAntigravityConfigPath,
  defaultAntigravityIdeConfigPath,
  defaultClaudeConfigPath,
  defaultClaudecodeConfigPath,
  defaultClineConfigPath,
  defaultCodexConfigPath,
  defaultContinueConfigPath,
  defaultCopilotConfigPath,
  defaultCursorConfigPath,
  defaultGeminiConfigPath,
  defaultGrokConfigPath,
  defaultHermesConfigPath,
  defaultJetbrainsConfigPath,
  defaultKimiCodeConfigPath,
  defaultKiroConfigPath,
  defaultOpencodeConfigPath,
  defaultOpenclawConfigPath,
  defaultQwenConfigPath,
  defaultTraeConfigPath,
  defaultTraeSoloConfigPath,
  defaultWindsurfConfigPath,
  defaultZedConfigPath
} from '../mcp/identity/paths.js';

